theme: jekyll-theme-cayman
title: Basic Battery Tracker
description: You can download the latest release of the application from there.
show_downloads: true
github:
  zip_url: https://github.com/CeamKrier/BasicBatteryTracker/raw/master/SimpleCounter/bin/Release/BatteryTracker.exe