theme: jekyll-theme-cayman
title: Basic Battery Tracker
description: You can download the latest release of the application from there.
show_downloads: true
github:
  zip_url: http://example.com/download.zip
